

Fitting to the TRANSVIR data prototype

# This is cleaning the TRANSVIR data

```{r}

# Clean data for fitting process
library(lubridate)
library(tidyverse)
library(dplyr)
library(fitdistrplus)

# Get fitted incidence rates
odd_people <- c("17-197B", "07-077B", "41-481E", "43-509K")

gambia_daily_cases <- read.csv(file = here::here("data", "transvir",  "gambia_covid_daily.csv") )
gambia_sero <- read.csv(file = here::here("data", "transvir", "David_serol.csv") ) %>% filter(!Participant_ID %in% odd_people)

gambian_case_add <- gambia_daily_cases %>% dplyr::mutate(date = ymd(date)) %>% 
    dplyr::mutate(variant = dplyr::case_when(
        date < dmy("01/07/2021") ~ "Pre-Delta",
        date >= dmy("01/07/2021") &  date < dmy("05/12/2021")~ "Delta",
        date >= dmy("05/12/2021") & date < dmy("01/06/2022")~ "Omicron"
    )
    )


gambian_case_delta <- gambian_case_add %>% filter(variant == "Delta") %>% 
    mutate(x = as.numeric(date - min(date)) )


gambia_sero_bleed <- gambia_sero %>% dplyr::select(Visits, Date) %>% summarise(n = n(), .by = c("Visits", "Date")) %>% 
    mutate(Date = ymd(Date))

gambia_sero_bleed %>% group_by(Visits) %>%  summarise(min(Date), max(Date))


gambia_sero <- read.csv(file = here::here("data","transvir", "David_serol.csv") ) %>% filter(!Participant_ID %in% odd_people)

serostatus_bleed <- gambia_sero %>% dplyr::select(Participant_ID, Visits, posneg_spike)

relabel_ss <- c("Pos" = "1", "Neg" = "0")

df_serostatus <- left_join(
    left_join(
        serostatus_bleed %>% filter(Visits == "V1") %>% rename(V1_ss = posneg_spike) %>% mutate(V1_ss = recode(V1_ss, !!!relabel_ss)) %>% dplyr::select(!Visits),
        serostatus_bleed %>% filter(Visits == "V2") %>% rename(V2_ss = posneg_spike) %>% mutate(V2_ss = recode(V2_ss, !!!relabel_ss)) %>% dplyr::select(!Visits)
    ),
    serostatus_bleed %>% filter(Visits == "V3") %>% rename(V3_ss = posneg_spike) %>% mutate(V3_ss = recode(V3_ss, !!!relabel_ss)) %>% dplyr::select(!Visits)
)

# Get meta data
gambia_meta <- read.csv(file = here::here("data", "transvir","full_demog_data.csv") )
gambia_meta_short <- gambia_meta %>% dplyr::select(Participant_ID,age_cat, Sex, vaccinated, vax_date)

gambian_covar <- gambia_meta_short %>% left_join(df_serostatus)

##

## Get information on pvnt and iga
gambia_pvn_raw <- read.csv(file = here::here("data", "transvir", "Pseudovirus_data_V1_V2_V3.csv") )
start_date <- dmy("17-03-2020")
start_day <- yday(start_date)
gambia_pvnt_b1 <- gambia_pvn_raw %>% dplyr::select(Participant_ID, V1_date, contains("ptna_Ancestral_V1")) %>% mutate(
    V1_date = as.numeric(dmy(V1_date) - start_date)) %>% rename(id = Participant_ID, time = V1_date, titre = ptna_Ancestral_V1) %>% 
    filter(!is.na(titre))
gambia_pvnt_b0 <- gambia_pvnt_b1 %>% dplyr::select(id) %>% mutate(time = 0, titre = 0)
gambia_pvnt <- bind_rows(gambia_pvnt_b0, gambia_pvnt_b1) %>% arrange(id, time) %>% mutate(titre = titre - 20) %>% 
    mutate(titre = case_when(
        titre < 0 ~ 0,
        TRUE ~ titre
    )) %>% mutate(titre = log10(titre + 1))

gambia_iga <- read.csv(file = here::here("data", "transvir", "IgA_data_V1_V2_V3.csv") )


# Get information on KNOWN infection dates
gambia_inf_dates <- read.csv(file = here::here("data", "transvir", "David_inf_data.csv") )

gambia_inf_dates_time <- gambia_inf_dates %>% 
    dplyr::mutate(first_inf_time = dplyr::case_when(
        First_positive_date < dmy("01/07/2021") ~ "Pre-Delta",
        First_positive_date >= dmy("01/07/2021") & First_positive_date < dmy("05/12/2021")~ "Delta",
        First_positive_date >= dmy("05/12/2021") & First_positive_date < dmy("01/06/2022")~ "Omicron"
        )
    ) %>%
    dplyr::mutate(second_inf_time = dplyr::case_when(
        second_positive_date < dmy("01/07/2021") ~ "Pre-Delta",
        second_positive_date >= dmy("01/07/2021") & second_positive_date < dmy("05/12/2021")~ "Delta",
        second_positive_date >= dmy("05/12/2021") & second_positive_date < dmy("01/06/2022")~ "Omicron"
    ) 
    )%>% 
    dplyr::mutate(third_inf_time = dplyr::case_when(
        third_positive_date < dmy("01/07/2021") ~ "Pre-Delta",
        third_positive_date >= dmy("01/07/2021") & third_positive_date < dmy("05/12/2021")~ "Delta",
        third_positive_date >= dmy("05/12/2021") & third_positive_date < dmy("01/06/2022")~ "Omicron"
    )
) 

gambia_known_inf_temp <- gambia_inf_dates_time %>% mutate(
    known_pre_delta = 
        case_when(
            second_inf_time == "Pre-Delta"~ second_positive_date,
            first_inf_time == "Pre-Delta"~ First_positive_date
            ),
  known_delta = 
        case_when(
            third_inf_time == "Delta"~ second_positive_date,
            second_inf_time == "Delta"~ second_positive_date,
            first_inf_time == "Delta"~ First_positive_date
            )
    ) %>% dplyr::select(Participant_ID, known_pre_delta, known_delta) %>%
     dplyr::select(id = Participant_ID, inf_time = known_pre_delta)  %>% mutate(
    inf_time = as.numeric(ymd(inf_time) - start_date)) 


gambia_known_inf <- gambia_pvnt %>% left_join(gambia_known_inf_temp) %>% dplyr::select(id, inf_time) %>% unique
 

# Get empirical distribution for incidence
gambia_daily_cases <- read.csv(file = here::here("data", "transvir",  "gambia_covid_daily.csv") )
gambia_daily_cases_ed <- gambia_daily_cases %>% filter(ymd(date) <   dmy("01/07/2021")) %>% mutate(
    date_time = as.numeric(ymd(date) - start_date)) %>% mutate(week = date_time %/% 14) %>% 
    summarise(total = sum(new_cases, na.rm = TRUE), .by = week) %>% 
    mutate(prop = total / sum(total)) %>% dplyr::select(week, prop)

exporate_prior <- data.frame(
    day = 1:(34*14),
    week = gambia_daily_cases_ed$week %>% map(~rep(.x, 14)) %>% unlist,
    prop = gambia_daily_cases_ed$prop %>% map(~rep(.x / 14, 14)) %>% unlist
)
exporate_prior %>%
    ggplot() + geom_col(aes(day, prop))


sample(exporate_prior$day, 1, prob = exporate_prior$prop)

exporate_prior$prop[3] %>% log

gambia_pvnt <- gambia_pvnt %>% mutate(id = as.numeric(factor(id)))


gambia_pvnt # This is the data to be used for the fitting
exporate_prior # This is an empirical distribution for the exposure based on the inciedence data. This is different to the siulation model which used a function. 


```


```{r}


#install.packages("devtools")
#library(devtools)
devtools::load_all()
library(rjmc)

# Define parameters, priors and support for ab kinetics model (a, b, c), observational model (sigma) and 
# the correlate of protection curve (beta0, beta1)
# Format is [param_name, lower_bound, upper_bound, prior_function (in R), parameter_1 in prior function, parameter_2 in prior function (if needed)]
# add_par_df adds to the par_tab
par_tab <- bind_rows( 
    add_par_df("a", 0.5, 4, "norm",  1.5, 0.5), # ab kinetics    
    add_par_df("b", 0, 1, "norm",  0.3, 0.05), # ab kinetics         
    add_par_df("c_slope", 0, 4, "unif", 0,  4), # ab kinetics       
    add_par_df("sigma_obs", 0.01, 1, "unif", 0.01, 1), # observational model
    add_par_df("beta0", -10, 10, "unif", -10, 10), # cop model (not used here)
    add_par_df("beta1", -10, 10, "unif", -10, 10) # cop model (not used here)
)



# Likelihood on the observational model, can be defined as anything [or put in c++]
evaluateLogLikelihood <- function(params, jump, jump_inf, covariance, datalist) {
    # datalist is data into the model which is useful
    N = datalist$N
    knownInfsVec =  datalist$knownInfsVec        
    knownInfsN = datalist$knownInfsN
    knownInfsDate = datalist$knownInfsDate
    endTitreTime = datalist$endTitreTime

    N_data = datalist$N_data
    initialTitreValue = datalist$initialTitreValue
    initialTitreTime = datalist$initialTitreTime
    titre_full = datalist$titre_full
    times_full = datalist$times_full
    id_full = datalist$id_full

    # jump is a vector representing vector E^\tau, the timing of exposure, if equal to -1 means not exposued
    # jump_inf is a binary vector representing non-infection (0) or infection (1) at time of exposure. 
    # jump_inf value is irrelevant if E^\tau is -1

    # Get values from the params vector
    a <- params[1]
    b <- params[2]
    c_slope <- params[3]
    c <- c_slope
    sigma_obs <- params[4]

    # Function to determine the antibody kinectics, A_jt
    ll <- 0
    for (i in 1:N_data) {
        # Find the estimated titre value, A_jt at the time of the titre bleed
        titre_val <- titre_full[i]
        time <- times_full[i]
        i_idx <- id_full[i]
        titre_init <- initialTitreValue[i_idx]
        titre_time_init <- initialTitreTime[i_idx]
        if (jump_inf[i_idx] == 0) {
            titre_est <- titre_init
        } else if ((jump_inf[i_idx] == 1) & (time < jump[i_idx])) {
            titre_est <- titre_init
        } else if ((jump_inf[i_idx] == 1) & (time >= jump[i_idx])){
            if ((time-jump[i_idx]) < 14) {
                titre_est <- titre_init + (log(exp(a) +  exp(c)) * (time-jump[i_idx]) / 14);
            } else {
                titre_est <- titre_init + (log(exp(a) * exp(-b/10 * ((time-jump[i_idx]) - 14)) + exp(c)));
            }
        }
        ## Observation model for individual i
        ## titre_val is Y_jt, titre_est is A_ji
        ll <- ll + dnorm(titre_val, titre_est, sigma_obs, log = TRUE)
    }
    ll
}

# Logistic correlate of protection model, this is added to the likelihood for each exposed person. Can be defined as anything
cop_func <- function(jump, jumpinf, params, initialTitreValue) {
    ll <- 0
    # COP parameters
    beta0 <- params[5]
    beta1 <- params[6]
 
    p <- 1.0 / (1.0 + exp(- (10 + 0 * initialTitreValue) ) )
    ll <- jumpinf * log(p) + (1 - jumpinf) * log(1 - p)

    ll
}


# This is slighty different to the simulated data as we have empirical priors for the exposure
createModelRJCMCFull <- function(ab_ll, par_tab, exporate_prior, cop_func) {
    model_type <- list()
    
    model_type$evaluateLogLikelihood <- ab_ll 
    model_type$lowerParSupport_fitted <- par_tab$lb
    model_type$upperParSupport_fitted <- par_tab$ub

    model_type$namesOfParameters <- par_tab$par_name

    model_type$samplePriorDistributions = function(datalist) {
        get_sample_non_centered(par_tab)
    }

    model_type$evaluateLogPrior <- function(params, jump, datalist) {
        cal_lprior_non_centered(par_tab, params)
    }

    model_type$copFunction <- cop_func

    model_type$initialiseJump <- function(datalist) {
        init_exposure <- c(datalist$knownInfsDate)
        init_exposure
    }

    model_type$exposureFunctionSample <- function() {
        sample(exporate_prior$day, 1, prob = exporate_prior$prop)
    }

    model_type$exposureFunctionDensity <- function(jump_i) {
        exporate_prior$prop[round(jump_i, 0)] %>% log
    }

    model_type
}


# This is slighty different to the simulated data as we have don't know any of the simualted data
generate_data_t <- function(data_titre_model, data_inf_model) {
    N <- data_titre_model$id %>% unique %>% length  
    N_data <- nrow(data_titre_model)
    titre_true <- data_titre_model$titre
    times_full <- data_titre_model$time
    id_full <- data_titre_model$id
    initialTitreValue <- data_titre_model %>% group_by(id) %>% filter(time == min(time)) %>% .[["titre"]]
    initialTitreTime <- data_titre_model %>% group_by(id) %>% filter(time == min(time)) %>% .[["time"]]
    endTitreTime <- data_titre_model %>% group_by(id) %>% filter(time == max(time)) %>% .[["time"]]

    # Determine known infections
    data_inf_model_temp <- data.frame(id = 1:N, known = 0, inf_time = -1)
    ids_known <- data_inf_model$id
    inftime_known <- data_inf_model$inf_time

    for (i in seq_len(length(ids_known))) {
        data_inf_model_temp[data_inf_model_temp$id == ids_known[i], "known"] <- 1
        data_inf_model_temp[data_inf_model_temp$id == ids_known[i], "inf_time"] <- inftime_known[i]
    }

    knownInfsVec <- data_inf_model_temp$known
    knownInfsN <- nrow(data_inf_model)
    knownInfsDate <- data_inf_model_temp$inf_time

    if (length(initialTitreValue) > N) {
        stop("ERROR: initialTitreValue wrong size ")
    }
    if (length(initialTitreTime) > N) {
        stop("ERROR: initialTitreTime wrong size ")
    }
    if (length(endTitreTime) > N) {
        stop("ERROR: endTitreTime wrong size ")
    }

    knownExpVec <- NA
    

    # Things needed, data for likelihood and sampler
    data_t <- list(
        N = N,
        N_data = N_data,
        initialTitreValue = initialTitreValue,
        initialTitreTime = initialTitreTime,
        endTitreTime = endTitreTime,
        titre_full = titre_true,
        times_full = times_full,
        id_full = id_full,

        knownExpVec = knownExpVec,
        knownInfsVec = knownInfsVec,
        knownInfsN = knownInfsN,
        knownInfsDate = knownInfsDate
    )
}

# Run reversible jump mcmc
runsaveRJMCMC <- function(filename, modelname, evaluateLogLikelihood, data_t_raw, par_tab, exp_prior, cop_func) {
    
    # Clean the data into a format for the sampler
    # data_titre_model format is [id, time, titre]
    # Generate the data_t format
    data_inf_model <- data.frame(id = vector(), inf_time = vector()) # none known
    data_t <- generate_data_t(gambia_pvnt, data_inf_model)

    # This function creates the list of functions needed for the rjmc_full_func
    model_define <- createModelRJCMCFull(evaluateLogLikelihood, par_tab, exp_prior, cop_func)

    # Settings used for the rjmcmc model, still playing around with optimal settings
    settings <-  list(
        numberChainRuns = 4,
        numberTempChains = 1, # not relevant
        iterations = 200000,
        burninPosterior = 100000,
        thin = 1,
        consoleUpdates = 100,
        numberFittedPar = model_define$namesOfParameters %>% length,
        onAdaptiveCov = TRUE,
        updatesAdaptiveCov = 100,
        burninAdaptiveCov = 1000,
        onAdaptiveTemp = TRUE,
        updatesAdaptiveTemp = 10,
        onDebug = FALSE,
        lowerParBounds = model_define$lowerParSupport_fitted,
        upperParBounds = model_define$upperParSupport_fitted,
        covarInitVal = 1e-2, # make very small if struggling to sample to beginning
        covarInitValAdapt = 1e-2, # make very small if struggling to sample to beginning
        covarMaxVal = 1, # decrease if struggling to sample in the middle
        runParallel = TRUE,
        numberCores = 4,
        lengthJumpVec = data_t$N,
        noGibbsSteps = 5
    )

    post <- rjmc_full_func(model = model_define, data = data_t, settings = settings)
    fitfull <- list(post = post,  model = model_define, data_t = data_t, par_tab = par_tab, exp_prior = exp_prior)

    dir.create(here::here("outputs", "fits", filename), showWarnings = FALSE)
    dir.create(here::here("outputs", "fits", filename, "figs"), showWarnings = FALSE)

    saveRDS(fitfull, here::here("outputs", "fits", filename, paste0("fit_", modelname, ".RDS")))
}


```

## Run according to the TARNSVIR data

```{r}

runsaveRJMCMC( "test/transvir", "wave1", evaluateLogLikelihood, gambia_pvnt, par_tab, exporate_prior, cop_func)

```

# Run the post-posterior plotting functions

```{r}


postprocessFigs("test/transvir", "wave1", 4)


```