
# Markdown to recreate the data in the methods rjmcmc paper

```{r}

# Loads all functions (need to download devtools 
#install.packages("devtools")
#library(devtools)
devtools::load_all()
library(rjmc)

# Define parameters, priors and support for ab kinetics model (a, b, c), observational model (sigma) and 
# the correlate of protection curve (beta0, beta1)
# Format is [param_name, lower_bound, upper_bound, prior_function (in R), parameter_1 in prior function, parameter_2 in prior function (if needed)]
# add_par_df adds to the par_tab
par_tab <- bind_rows( 
    add_par_df("a", 0.5, 4, "norm",  1.5, 0.5), # ab kinetics    
    add_par_df("b", 0, 1, "norm",  0.3, 0.05), # ab kinetics         
    add_par_df("c_slope", 0, 4, "unif", 0,  4), # ab kinetics       
    add_par_df("sigma_obs", 0.01, 1, "unif", 0.01, 1), # observational model
    add_par_df("beta0", -10, 10, "unif", -10, 10), # cop model
    add_par_df("beta1", -10, 10, "unif", -10, 10) # cop model
)

# Likelihood on the observational model, can be defined as anything [or put in c++]
evaluateLogLikelihood <- function(params, jump, jump_inf, expinf, covariance, datalist) {
    # datalist is data into the model which is useful
    N = datalist$N
    knownInfsVec =  datalist$knownInfsVec        
    knownInfsN = datalist$knownInfsN
    knownInfsDate = datalist$knownInfsDate
    endTitreTime = datalist$endTitreTime

    N_data = datalist$N_data
    initialTitreValue = datalist$initialTitreValue
    initialTitreTime = datalist$initialTitreTime
    titre_full = datalist$titre_full
    times_full = datalist$times_full
    id_full = datalist$id_full

    # jump is a vector representing vector E^\tau, the timing of exposure, if equal to -1 means not exposued
    # jump_inf is a binary vector representing non-infection (0) or infection (1) at time of exposure. 
    # jump_inf value is irrelevant if E^\tau is -1

    # Get values from the params vector
    a <- params[1]
    b <- params[2]
    c_slope <- params[3]
    c <- c_slope
    sigma_obs <- params[4]

    # Function to determine the antibody kinectics, A_jt
    ll <- 0
    for (i in 1:N_data) {
        # Find the estimated titre value, A_jt at the time of the titre bleed
        titre_val <- titre_full[i]
        time <- times_full[i]
        i_idx <- id_full[i]
        titre_init <- initialTitreValue[i_idx]
        titre_time_init <- initialTitreTime[i_idx]
        if (jump_inf[i_idx] == 0) {
            titre_est <- titre_init
        } else if ((jump_inf[i_idx] == 1) & (time < jump[i_idx])) {
            titre_est <- titre_init
        } else if ((jump_inf[i_idx] == 1) & (time >= jump[i_idx])){
            if ((time-jump[i_idx]) < 14) {
                titre_est <- titre_init + (log(exp(a) +  exp(c)) * (time-jump[i_idx]) / 14);
            } else {
                titre_est <- titre_init + (log(exp(a) * exp(-b/10 * ((time-jump[i_idx]) - 14)) + exp(c)));
            }
        }
        ## Observation model for individual i
        ## titre_val is Y_jt, titre_est is A_ji
        ll <- ll + dnorm(titre_val, titre_est, sigma_obs, log = TRUE)
    }
    ll
}

# Logistic correlate of protection model, this is added to the likelihood for each exposed person. Can be defined as anything
cop_func <- function(jump, jumpinf, params, initialTitreValue) {
    ll <- 0
    # COP parameters
    beta0 <- params[5]
    beta1 <- params[6]
 
    p <- 1.0 / (1.0 + exp(- (beta0 + beta1 * initialTitreValue) ) )
    ll <- jumpinf * log(p) + (1 - jumpinf) * log(1 - p)

    ll
}

# Define prior function for the force of exposure, can be anything
exp_prior <- data.frame(
    lb = "1", # lower bound
    ub = "120", # upper bound
    func = "unif", # functional form
    par1 = "1", # parameter 1 of functional form
    par2 = "120" # parameter 2 of functional form
)

# Run reversible jump mcmc
runsaveRJMCMC <- function(modelname, modelname_sim, obs_er, prob_known, evaluateLogLikelihood, par_tab, exp_prior, cop_func, known_exp = FALSE) {
    
    # Clean the data into a format for the sampler
    # data_titre_model format is [id, time, titre]
    data_titre_model <- clean_simulated_rjmcmc(modelname_sim, obs_er, prob_known, known_exp)
    
    if (known_exp) {
        modeli <- readRDS(here::here("outputs", "sim_data", modelname_sim, "inputs.RDS"))
        known_exp_t <- modeli$simpar$exp 
    } else {
        known_exp_t <- NULL
    }
     
    # data_inf_model format is [id, inf_time]
    # Generate the data_t format
    data_t <- generate_data_t(data_titre_model, data_inf_model = NULL, known_exp = known_exp_t)

    # This function creates the list of functions needed for the rjmc_full_func
    model_define <- createModelRJCMCFull(evaluateLogLikelihood, par_tab, cop_func)
    model_define <- addExposurePrior(model_define, data_t, exp_prior, type = "func")
    model_define <- addFunctionTitreExp(model_define)

    # Settings used for the rjmcmc model, still playing around with optimal settings
    settings <-  list(
        numberChainRuns = 4,
        numberTempChains = 1, # not relevant
        iterations = 400000,
        burninPosterior = 200000,
        thin = 100,
        consoleUpdates =  5,
        numberFittedPar = model_define$namesOfParameters %>% length,
        onAdaptiveCov = TRUE,
        updatesAdaptiveCov = 100,
        burninAdaptiveCov = 1000,
        onAdaptiveTemp = TRUE,
        updatesAdaptiveTemp = 10,
        onDebug = FALSE,
        lowerParBounds = model_define$lowerParSupport_fitted,
        upperParBounds = model_define$upperParSupport_fitted,
        covarInitVal = 1e-2, # make very small if struggling to sample to beginning
        covarInitValAdapt = 1e-2, # make very small if struggling to sample to beginning
        covarMaxVal = 1, # decrease if struggling to sample in the middle
        runParallel = FALSE,
        numberCores = 4,
        lengthJumpVec = data_t$N,
        noGibbsSteps = 5
    )

    post <- rjmc_full_func(model = model_define, data = data_t, settings = settings)
    fitfull <- list(post = post,  model = model_define, data_t = data_t, par_tab = par_tab, exp_prior = exp_prior)

    dir.create(here::here("outputs", "fits", modelname_sim), showWarnings = FALSE)
    dir.create(here::here("outputs", "fits", modelname_sim, modelname), showWarnings = FALSE)
    dir.create(here::here("outputs", "fits", modelname_sim, modelname, "figs"), showWarnings = FALSE)

    saveRDS(fitfull, here::here("outputs", "fits", modelname_sim, modelname, paste0("fit_", "obs_", obs_er, ".RDS")))
}

```

# Run all scenarios (CES) for rj-mcmc methods paper


```{r}

# Run on the exposure inferred cycle
runsaveRJMCMC( "inferExp", "cesCOP_notd", "0.1", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func)
runsaveRJMCMC( "inferExp", "cesCOP_notd", "0.3", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func)
runsaveRJMCMC( "inferExp", "cesCOP_notd", "0.5", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func)

postprocessFigs_sim("inferExp", "cesCOP_notd", "0.1", 4)
postprocessFigs_sim("inferExp", "cesCOP_notd", "0.3", 4)
postprocessFigs_sim("inferExp", "cesCOP_notd", "0.5", 4)

runsaveRJMCMC( "inferExp", "cesNoCOP_notd", "0.1", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func)
runsaveRJMCMC( "inferExp", "cesNoCOP_notd", "0.3", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func)
runsaveRJMCMC( "inferExp", "cesNoCOP_notd", "0.5", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func)

postprocessFigs_sim("inferExp", "cesNoCOP_notd", "0.1", 4)
postprocessFigs_sim("inferExp", "cesNoCOP_notd", "0.3", 4)
postprocessFigs_sim("inferExp", "cesNoCOP_notd", "0.5", 4)

# Run on the exposure known cycle
runsaveRJMCMC( "knownExp", "cesCOP_notd", "0.1", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func, TRUE)
runsaveRJMCMC( "knownExp", "cesCOP_notd", "0.3", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func, TRUE)
runsaveRJMCMC( "knownExp", "cesCOP_notd", "0.5", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func, TRUE)

postprocessFigs_sim("knownExp", "cesCOP_notd", "0.1", 4)
postprocessFigs_sim("knownExp", "cesCOP_notd", "0.3", 4)
postprocessFigs_sim("knownExp", "cesCOP_notd", "0.5", 4)


runsaveRJMCMC( "knownExp", "cesNoCOP_notd", "0.1", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func, TRUE)
runsaveRJMCMC( "knownExp", "cesNoCOP_notd", "0.3", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func, TRUE)
runsaveRJMCMC( "knownExp", "cesNoCOP_notd", "0.5", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func, TRUE)

postprocessFigs_sim("knownExp", "cesNoCOP_notd", "0.1", 4)
postprocessFigs_sim("knownExp", "cesNoCOP_notd", "0.3", 4)
postprocessFigs_sim("knownExp", "cesNoCOP_notd", "0.5", 4)


````

# Rerun figures only

```{r}

postprocessFigs_sim("inferExp", "cesCOP_notd", "0.1", 4)
postprocessFigs_sim("inferExp", "cesCOP_notd", "0.3", 4)
postprocessFigs_sim("inferExp", "cesCOP_notd", "0.5", 4)

postprocessFigs_sim("inferExp", "cesNoCOP_notd", "0.1", 4)
postprocessFigs_sim("inferExp", "cesNoCOP_notd", "0.3", 4)
postprocessFigs_sim("inferExp", "cesNoCOP_notd", "0.5", 4)

postprocessFigs_sim("knownExp", "cesCOP_notd", "0.1", 4)
postprocessFigs_sim("knownExp", "cesCOP_notd", "0.3", 4)
postprocessFigs_sim("knownExp", "cesCOP_notd", "0.5", 4)

postprocessFigs_sim("knownExp", "cesNoCOP_notd", "0.1", 4)
postprocessFigs_sim("knownExp", "cesNoCOP_notd", "0.3", 4)
postprocessFigs_sim("knownExp", "cesNoCOP_notd", "0.5", 4)

```