
# Markdown to recreate the data in the methods rjmcmc paper

```{r}

devtools::load_all()
library(tidyverse)
library(brms)
library(furrr)
library(rjmc)
library(serosim)
library(furrr)
library(patchwork)
library(pushoverr)
source("r/utils.r")
source("r/postprocess.r")

plan(multisession, workers = 12)


# Define parameters and priors for ab kinetics model
par_tab <- bind_rows( 
    # regression parameters
    add_par_df("a", 0.5, 4, "norm",  1.5, 0.5), # has to be mininum boost      
    add_par_df("b", 0, 1, "norm",  0.3, 0.05), # has to be mininum boost        
    add_par_df("c_slope", 0, 4, "unif", 0,  4), # has to be mininum boost     
    add_par_df("sigma_obs", 0.01, 1, "unif", 0.01, 1),
    add_par_df("beta0", -10, 10, "unif", -10, 10),
    add_par_df("beta1", -10, 10, "unif", -10, 10)
)


# Likelihood on ab kinetics
evaluateLogLikelihood <- function(params, jump, jump_inf, covariance, datalist) {

    N = datalist$N
    knownInfsVec =  datalist$knownInfsVec        
    knownInfsN = datalist$knownInfsN
    knownInfsDate = datalist$knownInfsDate
    endTitreTime = datalist$endTitreTime

    N_data = datalist$N_data
    initialTitreValue = datalist$initialTitreValue
    initialTitreTime = datalist$initialTitreTime
    titre_full = datalist$titre_full
    times_full = datalist$times_full
    id_full = datalist$id_full



    # Matrices
    a <- params[1]
    b <- params[2]
    c_slope <- params[3]

    c <- c_slope
    sigma_obs <- params[4]

    ll <- 0
    # Likelihood of antibody kinetics
    for (i in 1:N_data) {
        titre_val <- titre_full[i]
        time <- times_full[i]
        i_idx <- id_full[i]
        titre_init <- initialTitreValue[i_idx]
        titre_time_init <- initialTitreTime[i_idx]
        if (jump_inf[i_idx] == 0) {
            titre_est <- titre_init
        } else if ((jump_inf[i_idx] == 1) & (time < jump[i_idx])) {
            titre_est <- titre_init
        } else if ((jump_inf[i_idx] == 1) & (time >= jump[i_idx])){
            if ((time-jump[i_idx]) < 14) {
                titre_est <- titre_init + (log(exp(a) +  exp(c)) * (time-jump[i_idx]) / 14);
            } else {
                titre_est <- titre_init + (log(exp(a) * exp(-b/10 * ((time-jump[i_idx]) - 14)) + exp(c)));
            }
        }
        ll <- ll + dnorm(titre_val, titre_est, sigma_obs, log = TRUE)
    }
    ll
}

# Logistic correlate of protection model
cop_func <- function(jump, jumpinf, params, initialTitreValue) {
    ll <- 0
    beta0 <- params[5]
    beta1 <- params[6]
 
   # for (i in 1:N_data) {
    p <- 1.0 / (1.0 + exp(- (beta0 + beta1 * initialTitreValue) ) )
    ll <- jumpinf * log(p) + (1 - jumpinf) * log(1 - p)

   # }
    ll
}

# Run reversible jump mcmc
runsaveRJMCMC <- function(modelname, modelname_sim, obs_er, prob_known, evaluateLogLikelihood, par_tab, exp_prior, cop_func, known_exp = FALSE) {
    # settings used for the ptmc model 
    data_t <- clean_simulated_rjmcmc(modelname_sim, obs_er, prob_known, known_exp)
    model_define <- createModelRJCMCFull(evaluateLogLikelihood, par_tab, exp_prior, cop_func)

    settings <-  list(
        numberChainRuns = 4,
        numberTempChains = 1,
        iterations = 400000,
        burninPosterior = 200000,
        thin = 100,
        consoleUpdates =  100,
        numberFittedPar = 6,
        onAdaptiveCov = TRUE,
        updatesAdaptiveCov = 100,
        burninAdaptiveCov = 1000,
        onAdaptiveTemp = TRUE,
        updatesAdaptiveTemp = 10,
        onDebug = FALSE,
        lowerParBounds = model_define$lowerParSupport_fitted,
        upperParBounds = model_define$upperParSupport_fitted,
        covarInitVal = 1e-2, # make very small if struggling to sample to beginning
        covarInitValAdapt = 1e-2, # make very small if struggling to sample to beginning
        covarMaxVal = 1, # decrease if struggling to sample in the middle
        runParallel = TRUE,
        numberCores = 4,
        lengthJumpVec = data_t$N,
        noGibbsSteps = 5
    )


    post <- rjmc_full_func(model = model_define, data = data_t, settings = settings)
    fitfull <- list(post = post,  model = model_define, data_t = data_t, par_tab = par_tab, exp_prior = exp_prior)

    dir.create(here::here("outputs", "fits", modelname_sim))
    dir.create(here::here("outputs", "fits", modelname_sim, modelname))
    dir.create(here::here("outputs", "fits", modelname_sim, modelname, "figs"))

    saveRDS(fitfull, here::here("outputs", "fits", modelname_sim, modelname, paste0("fit_", "obs_", obs_er, ".RDS")))
}


# Simulation recovery for ces
# Define priors on incidence
exp_prior <- data.frame(
    lb = "1",
    ub = "120",
    func = "unif",
    par1 = "1",
    par2 = "120"
)

```

# Run all scenarios (CES)
```{r}


# Run on the exposure inferred cycle
runsaveRJMCMC( "inferExp", "cesCOP_notd", "0.1", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func)
runsaveRJMCMC( "inferExp", "cesCOP_notd", "0.3", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func)
runsaveRJMCMC( "inferExp", "cesCOP_notd", "0.5", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func)

postprocessFigs("inferExp", "cesCOP_notd", "0.1", 4)
postprocessFigs("inferExp", "cesCOP_notd", "0.3", 4)
postprocessFigs("inferExp", "cesCOP_notd", "0.5", 4)

runsaveRJMCMC( "inferExp", "cesNoCOP_notd", "0.1", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func)
runsaveRJMCMC( "inferExp", "cesNoCOP_notd", "0.3", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func)
runsaveRJMCMC( "inferExp", "cesNoCOP_notd", "0.5", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func)

postprocessFigs("inferExp", "cesNoCOP_notd", "0.1", 4)
postprocessFigs("inferExp", "cesNoCOP_notd", "0.3", 4)
postprocessFigs("inferExp", "cesNoCOP_notd", "0.5", 4)

# Run on the exposure known cycle
runsaveRJMCMC( "knownExp", "cesCOP_notd", "0.1", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func, TRUE)
runsaveRJMCMC( "knownExp", "cesCOP_notd", "0.3", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func, TRUE)
runsaveRJMCMC( "knownExp", "cesCOP_notd", "0.5", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func, TRUE)

postprocessFigs("knownExp", "cesCOP_notd", "0.1", 4)
postprocessFigs("knownExp", "cesCOP_notd", "0.3", 4)
postprocessFigs("knownExp", "cesCOP_notd", "0.5", 4)


runsaveRJMCMC( "knownExp", "cesNoCOP_notd", "0.1", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func, TRUE)
runsaveRJMCMC( "knownExp", "cesNoCOP_notd", "0.3", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func, TRUE)
runsaveRJMCMC( "knownExp", "cesNoCOP_notd", "0.5", 0, evaluateLogLikelihood, par_tab, exp_prior, cop_func, TRUE)

postprocessFigs("knownExp", "cesNoCOP_notd", "0.1", 4)
postprocessFigs("knownExp", "cesNoCOP_notd", "0.3", 4)
postprocessFigs("knownExp", "cesNoCOP_notd", "0.5", 4)


````

# Rerun figures only

```{r}

postprocessFigs("inferExp", "cesCOP_notd", "0.1", 4)
postprocessFigs("inferExp", "cesCOP_notd", "0.3", 4)
postprocessFigs("inferExp", "cesCOP_notd", "0.5", 4)

postprocessFigs("inferExp", "cesNoCOP_notd", "0.1", 4)
postprocessFigs("inferExp", "cesNoCOP_notd", "0.3", 4)
postprocessFigs("inferExp", "cesNoCOP_notd", "0.5", 4)

postprocessFigs("knownExp", "cesCOP_notd", "0.1", 4)
postprocessFigs("knownExp", "cesCOP_notd", "0.3", 4)
postprocessFigs("knownExp", "cesCOP_notd", "0.5", 4)

postprocessFigs("knownExp", "cesNoCOP_notd", "0.1", 4)
postprocessFigs("knownExp", "cesNoCOP_notd", "0.3", 4)
postprocessFigs("knownExp", "cesNoCOP_notd", "0.5", 4)

```