# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_rjmc <- function(model, dataList, settings, update_ind, RJMCpar, i) {
    .Call('_rjmc_run_rjmc', PACKAGE = 'rjmc', model, dataList, settings, update_ind, RJMCpar, i)
}

