# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_rjmc_sero <- function(model, dataList, settings, update_ind, RJMCpar, i, seed = -1L) {
    .Call('_serojump_run_rjmc_sero', PACKAGE = 'serojump', model, dataList, settings, update_ind, RJMCpar, i, seed)
}

